# Generated by Django 5.1.4 on 2025-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_order_branches_number_order_first_time_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='students_fees',
        ),
        migrations.AddField(
            model_name='order',
            name='students_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Students number'),
        ),
        migrations.AddField(
            model_name='recurringuserplan',
            name='branches_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Branches Number'),
        ),
        migrations.AddField(
            model_name='recurringuserplan',
            name='students_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Students number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branches_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Branches Number'),
        ),
    ]
