# Generated by Django 5.1.4 on 2025-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_order_students_fees_order_students_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_trial_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Free Trial Days'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='activated_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Activated Date'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='canceled_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='trial_end_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Trial End Date'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='trial_start_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Trial Start Date'),
        ),
    ]
