# Generated by Django 5.1.4 on 2025-02-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_userplancancelationreasons_reason_ar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlanCancelationReasons',
            new_name='UserPlanCancellationReason',
        ),
    ]
