# Generated by Django 5.1.4 on 2025-02-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_rename_userplancancelationreasons_userplancancellationreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='cancelation_reason',
        ),
        migrations.AddField(
            model_name='userplan',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plans.userplancancellationreason', verbose_name='Cancellation Reason'),
        ),
    ]
