# Generated by Django 5.1.4 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_userplan_cancelation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Paid'),
        ),
    ]
