# Generated by Django 5.1.4 on 2025-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_userplan_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_time_fees',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='First time fees'),
        ),
    ]
