# Generated by Django 5.1.4 on 2025-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_order_first_time_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'completed'), (3, 'not valid'), (4, 'canceled'), (5, 'returned'), (6, 'pending')], default=1, verbose_name='status'),
        ),
    ]
