# Generated by Django 5.1.4 on 2024-12-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_planpricing_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='branches',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
