# Generated by Django 5.1.4 on 2025-01-05 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_plan_description_ar_plan_description_en_plan_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpricing',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
