# Generated by Django 5.1.4 on 2025-01-19 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_userplan_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_per_student',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
